### PR TITLE
fix tests

### PR DESCRIPTION
**Pull request by achille-roussel**
The v1 API doesn't exist anymore, moving to v3 fixed the tests.

### CODE REVIEW

**Comment by achille-roussel** [comment]
We also have no customers using the v2 API, let's get rid of it and drop support? (it's deprecated) @sperand-io

**Comment by hankim813** [comment]
if nobody is using it, we should deprecate it while nobody is using it :)

So basically the integration should only support v3 cc @sperand-io @achille-roussel

**Comment by achille-roussel** [comment]
Works for me!

**Comment by achille-roussel** [comment]
Will do 👍  Thanks for the review!

**Pull request merged**
